
name: Test commit
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup NodeJs
        uses: actions/setup-node@v2.1.5
        with:
          node-version: '16.x'
          
      - name: Install dependencies
        run: cd contract && npm install

      - name: Run Tests on contract
        run: cd contract && npx hardhat test
